set -g prefix C-a
unbind C-b
# 连按两次 Ctrl + a 向终端发送原有的 Ctrl + a 命令
bind C-a send-prefix

bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
set -g mouse

set -g status-right "[#{pane_index}#{pane_id}] | %Y-%m-%d %H:%M"

set -g extended-keys on
set -g extended-keys-format csi-u

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
